"""
Smart BI Agent — Prompt Guard
Architecture v3.1 | Security Layer 5 | Threats: T4(conv poisoning), T37

PURPOSE:
    Sanitize conversation history before injecting into LLM prompts.
    Over multiple turns, an attacker could gradually manipulate the
    conversation context to bypass security controls.

CONTROLS:
    - Strip instruction-like patterns from conversation history
    - Truncate each turn to max 500 chars (prevent context stuffing)
    - Limit total conversation to 20 turns (T37)
    - Inject only structured summaries, not raw user input
    - Detect common prompt injection patterns
"""

from __future__ import annotations

import re
from typing import Optional

from app.config import get_settings


# =============================================================================
# Prompt Injection Detection Patterns
# =============================================================================

# Patterns that indicate attempted prompt injection in user questions
# or conversation history. These are stripped from context.
INJECTION_PATTERNS: list[re.Pattern] = [
    # Direct instruction override attempts
    re.compile(r"ignore\s+(all\s+)?(previous|prior|above)\s+(instructions?|rules?|prompts?)", re.I),
    re.compile(r"disregard\s+(all\s+)?(previous|prior|above)", re.I),
    re.compile(r"forget\s+(all\s+)?(previous|prior|above|your)\s+(instructions?|rules?)", re.I),

    # System prompt extraction
    re.compile(r"(what|show|print|reveal|display)\s+(is\s+)?(your|the)\s+system\s+(prompt|instructions?)", re.I),
    re.compile(r"repeat\s+(your|the)\s+(system\s+)?(prompt|instructions?)", re.I),

    # Role manipulation
    re.compile(r"you\s+are\s+now\s+", re.I),
    re.compile(r"act\s+as\s+(if\s+you\s+are\s+|a\s+)", re.I),
    re.compile(r"pretend\s+(you\s+are|to\s+be)\s+", re.I),
    re.compile(r"switch\s+to\s+\w+\s+mode", re.I),

    # Security bypass attempts
    re.compile(r"(bypass|skip|disable|turn\s+off|ignore)\s+(security|validation|safety|filter)", re.I),
    re.compile(r"(execute|run)\s+(this\s+)?(command|query|code)\s+(directly|without)", re.I),

    # SQL injection via conversation
    re.compile(r"(INSERT|UPDATE|DELETE|DROP|ALTER|TRUNCATE|GRANT|REVOKE)\s+", re.I),

    # Data exfiltration attempts
    re.compile(r"(send|email|post|upload|transmit)\s+(the\s+)?(data|results?|output)", re.I),
]


def detect_injection(text: str) -> list[str]:
    """
    Detect prompt injection patterns in text.

    Args:
        text: User question or conversation turn.

    Returns:
        List of matched pattern descriptions (empty if clean).
    """
    if not text:
        return []

    matches = []
    for pattern in INJECTION_PATTERNS:
        if pattern.search(text):
            matches.append(pattern.pattern)

    return matches


def strip_injection_patterns(text: str) -> str:
    """
    Remove detected injection patterns from text.

    Doesn't reject the text entirely — just removes the malicious parts.
    This allows legitimate questions that accidentally match patterns
    to still work (e.g., "Can you show me DELETE operations in the audit log?").

    Args:
        text: Raw user input or conversation turn.

    Returns:
        Cleaned text with injection patterns removed.
    """
    if not text:
        return ""

    cleaned = text
    for pattern in INJECTION_PATTERNS:
        cleaned = pattern.sub("[FILTERED]", cleaned)

    return cleaned.strip()


# =============================================================================
# Conversation History Sanitization
# =============================================================================

def sanitize_conversation_turn(
    question: Optional[str] = None,
    sql_query: Optional[str] = None,
    result_summary: Optional[str] = None,
    max_chars: Optional[int] = None,
) -> dict[str, str]:
    """
    Sanitize a single conversation turn for prompt context.

    Each turn is converted to a structured summary rather than
    raw user input. This limits the attack surface for gradual
    prompt manipulation (T37).

    Args:
        question: The user's question for this turn.
        sql_query: The generated SQL (for context).
        result_summary: Brief summary of results (e.g., "150 rows, 3 columns").
        max_chars: Max chars per field (default from config).

    Returns:
        Sanitized turn dict suitable for prompt injection.
    """
    settings = get_settings()
    limit = max_chars or settings.MAX_CONVERSATION_TURN_CHARS

    sanitized = {}

    if question:
        # Strip injection patterns from the question
        clean_q = strip_injection_patterns(question)
        sanitized["question"] = _truncate(clean_q, limit)

    if sql_query:
        # SQL is generated by us, but could be echoed back maliciously
        sanitized["sql"] = _truncate(sql_query, limit)

    if result_summary:
        # Result summary should be short structured text
        sanitized["result"] = _truncate(result_summary, limit)

    return sanitized


def sanitize_conversation_history(
    turns: list[dict],
    max_turns: Optional[int] = None,
) -> list[dict[str, str]]:
    """
    Sanitize an entire conversation history for prompt context.

    Enforces:
        - Maximum turn count (T37: 20 turns)
        - Per-turn character limit (500 chars)
        - Injection pattern removal
        - Structured summary format

    Args:
        turns: List of conversation turn dicts.
        max_turns: Max turns to include (default from config).

    Returns:
        List of sanitized turn dicts, most recent last.
    """
    settings = get_settings()
    limit = max_turns or settings.MAX_CONVERSATION_TURNS

    # Take the most recent turns (drop oldest if over limit)
    recent = turns[-limit:] if len(turns) > limit else turns

    sanitized = []
    for turn in recent:
        clean = sanitize_conversation_turn(
            question=turn.get("question"),
            sql_query=turn.get("sql_query"),
            result_summary=turn.get("result_summary"),
        )
        if clean:  # Skip empty turns
            sanitized.append(clean)

    return sanitized


def is_conversation_at_limit(turn_count: int) -> bool:
    """
    Check if a conversation has reached its turn limit (T37).

    Args:
        turn_count: Current number of turns in the conversation.

    Returns:
        True if no more turns should be added.
    """
    settings = get_settings()
    return turn_count >= settings.MAX_CONVERSATION_TURNS


# =============================================================================
# Helpers
# =============================================================================

def _truncate(text: str, max_chars: int) -> str:
    """Truncate text to max_chars with ellipsis indicator."""
    if len(text) <= max_chars:
        return text
    return text[:max_chars - 3] + "..."
