"""
Smart BI Agent — SQL Validator (5-step core pipeline)
Architecture v3.1 | Layer 6 (Query Processing) | Threats: T5, T6, T7

PURPOSE:
    Validates ALL LLM-generated SQL before execution against user databases.
    This is the primary security gate — no SQL reaches the DB without passing.

PIPELINE (5 essential steps for Phase 4C):
    1. Parse with sqlglot (confirm valid SQL syntax)
    2. Block DDL/DML (no CREATE, DROP, ALTER, INSERT, UPDATE, DELETE, TRUNCATE)
    3. Block multiple statements (no semicolon stacking)
    4. Verify all referenced tables exist in the connection's allowed schema
    5. Inject/cap LIMIT if missing (default from connection's max_rows)

FUTURE (Phase 5+):
    6. Block system catalogs
    7. Dialect-specific function blocklists
    8. CTE recursive validation
    9. Column-level permission check
   10. Semantic JOIN check

SECURITY:
    SQLValidationError is intentionally vague to the client (T10).
    Full SQL and failure reason are logged server-side only.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Optional

import sqlglot
from sqlglot import Expression, exp
from sqlglot.errors import ParseError

from app.errors.exceptions import SQLValidationError
from app.logging.structured import get_logger

log = get_logger(__name__)


@dataclass
class ValidationResult:
    """Result of SQL validation pipeline."""
    valid: bool
    sql: str                        # The (potentially modified) SQL
    tables_referenced: list[str]    # Tables found in the query
    limit_injected: bool = False    # Whether we added/capped a LIMIT
    error: Optional[str] = None     # Internal error detail (never sent to client)


# ─── Blocked Statement Types ─────────────────────────────────────────────────

_BLOCKED_TYPES: set[type[Expression]] = {
    exp.Create,
    exp.Drop,
    exp.Alter,
    exp.Insert,
    exp.Update,
    exp.Delete,
    exp.Command,       # TRUNCATE, GRANT, REVOKE, etc.
}

# Additional keywords caught by regex (sqlglot may parse some as Command)
_BLOCKED_KEYWORDS_RE = re.compile(
    r"\b(TRUNCATE|GRANT|REVOKE|COPY|VACUUM|REINDEX|CLUSTER)\b",
    re.IGNORECASE,
)


def validate_sql(
    raw_sql: str,
    allowed_tables: set[str],
    max_rows: int = 10_000,
    dialect: str = "postgres",
) -> ValidationResult:
    """
    Run the 5-step SQL validation pipeline.

    Args:
        raw_sql: The SQL string generated by the LLM.
        allowed_tables: Set of table names the user is allowed to query.
        max_rows: Maximum rows to allow (LIMIT cap).
        dialect: SQL dialect for parsing (default: postgres).

    Returns:
        ValidationResult with valid=True and the (potentially modified) SQL,
        or valid=False with an internal error description.

    Raises:
        SQLValidationError: If the SQL fails any validation step.
    """
    sql = raw_sql.strip().rstrip(";").strip()

    if not sql:
        raise SQLValidationError(
            message="No SQL query was generated.",
            detail="LLM returned empty SQL",
        )

    # ─── Step 1: Parse with sqlglot ──────────────────────────────────────
    try:
        parsed = sqlglot.parse(sql, dialect=dialect)
    except ParseError as exc:
        log.warning("sql_validator.parse_failed", error=str(exc), sql=sql[:200])
        raise SQLValidationError(
            message="The generated query has invalid syntax.",
            detail=f"sqlglot parse error: {exc}",
        )

    if not parsed:
        raise SQLValidationError(
            message="No valid SQL statement found.",
            detail="sqlglot returned empty parse result",
        )

    # ─── Step 2: Block multiple statements ───────────────────────────────
    if len(parsed) > 1:
        log.warning("sql_validator.multi_statement", count=len(parsed), sql=sql[:200])
        raise SQLValidationError(
            message="Only single SELECT queries are allowed.",
            detail=f"Multiple statements detected: {len(parsed)}",
        )

    tree = parsed[0]

    # ─── Step 3: Block DDL/DML ───────────────────────────────────────────
    # Check AST node type
    for node in tree.walk():
        if type(node) in _BLOCKED_TYPES:
            type_name = type(node).__name__
            log.warning("sql_validator.blocked_type", type=type_name, sql=sql[:200])
            raise SQLValidationError(
                message="Only SELECT queries are allowed. Data modification is blocked.",
                detail=f"Blocked statement type: {type_name}",
            )

    # Regex fallback for keywords sqlglot may parse as generic Command
    if _BLOCKED_KEYWORDS_RE.search(sql):
        match = _BLOCKED_KEYWORDS_RE.search(sql)
        keyword = match.group(0) if match else "unknown"
        log.warning("sql_validator.blocked_keyword", keyword=keyword, sql=sql[:200])
        raise SQLValidationError(
            message="Only SELECT queries are allowed.",
            detail=f"Blocked keyword detected: {keyword}",
        )

    # Must be a SELECT (or WITH...SELECT)
    if not isinstance(tree, (exp.Select, exp.Union, exp.Intersect, exp.Except)):
        # Check for CTE (WITH clause wrapping a SELECT)
        if isinstance(tree, exp.CTE) or (hasattr(tree, "this") and isinstance(tree.this, exp.Select)):
            pass  # CTEs are allowed
        else:
            type_name = type(tree).__name__
            log.warning("sql_validator.not_select", type=type_name, sql=sql[:200])
            raise SQLValidationError(
                message="Only SELECT queries are allowed.",
                detail=f"Root statement is {type_name}, not SELECT",
            )

    # ─── Step 4: Verify referenced tables exist ─────────────────────────
    tables_referenced: list[str] = []
    for table in tree.find_all(exp.Table):
        table_name = table.name
        if table_name:
            tables_referenced.append(table_name)

    # If allowed_tables is non-empty, enforce it
    if allowed_tables:
        # Case-insensitive comparison
        allowed_lower = {t.lower() for t in allowed_tables}
        for tbl in tables_referenced:
            if tbl.lower() not in allowed_lower:
                log.warning(
                    "sql_validator.unauthorized_table",
                    table=tbl,
                    allowed=list(allowed_tables)[:10],
                    sql=sql[:200],
                )
                raise SQLValidationError(
                    message="The query references a table you don't have access to.",
                    detail=f"Table '{tbl}' not in allowed set",
                )

    # ─── Step 5: Inject/cap LIMIT ────────────────────────────────────────
    limit_injected = False

    # Find existing LIMIT clause
    existing_limit = tree.find(exp.Limit)

    if existing_limit is None:
        # No LIMIT — inject one
        tree = tree.limit(max_rows)
        limit_injected = True
    else:
        # LIMIT exists — cap it if too large
        try:
            limit_val = int(existing_limit.expression.this)
            if limit_val > max_rows:
                existing_limit.expression.set("this", str(max_rows))
                limit_injected = True
        except (ValueError, AttributeError):
            # Can't parse limit value — leave as-is
            pass

    # Generate the final SQL string
    final_sql = tree.sql(dialect=dialect, pretty=True)

    log.info(
        "sql_validator.passed",
        tables=tables_referenced,
        limit_injected=limit_injected,
        sql_length=len(final_sql),
    )

    return ValidationResult(
        valid=True,
        sql=final_sql,
        tables_referenced=tables_referenced,
        limit_injected=limit_injected,
    )
